export const depotItems = [
  // =================================================================
  // == Items from Image
  // =================================================================
  {
    id: "rpi4_2gb",
    name: "Raspberry Pi 4 Model B/2GB",
    description: "The workhorse of the modern maker. A powerful single-board computer for all your project needs.",
    price: 78.9,
    quantity: 10,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/1977/5047/2GB-9003__22392.1560436211__50222.1561146603__85865.1736961428.jpg?c=2",
    category: "Compute",
  },
  {
    id: "rpi_microsd_32gb",
    name: "Official Raspberry Pi 32GB microSD Card",
    description: "High-speed, reliable storage for your Raspberry Pi projects.",
    price: 13.95,
    quantity: 10,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/3854/12396/RPF_SD_card_128Gb__56729.1735941612.jpg?c=2",
    category: "Compute",
  },
  {
    id: "led_assorted_20",
    name: "LED - Assorted (20 pack)",
    description: "A variety of colors to bring your projects to life.",
    price: 5.95,
    quantity: 2,
    max_quantity: 2,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/2945/8910/12062-01__18421.1654024449.jpg?c=2",
    category: "Components",
  },
  {
    id: "tactile_switch_20",
    name: "Adafruit Tactile Button Switch (6mm) - 20 Pack",
    description: "Clicky and responsive buttons for user input.",
    price: 3.45,
    quantity: 2,
    max_quantity: 2,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/409/1057/apisf83yo__32461.1554985250.jpg?c=2",
    category: "Components",
  },
  {
    id: "yl69_hygrometer",
    name: "YL-69 Soil Hygrometer Humidity Detection Module",
    description: "Measures soil moisture to keep your plants happy.",
    price: 4.95,
    quantity: 2,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/2370/6526/ODSeven_1_ec300a31-925a-49ca-8277-c901b3c3d0d4_400x__03753.1598895203.jpg?c=2",
    category: "Sensors",
  },
  {
    id: "elecfreaks_water_pump",
    name: "ElecFreaks 3V Vertical Water Pump",
    description: "A small pump for all your watering and liquid-moving needs.",
    price: 5.45,
    quantity: 2,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/3797/12322/img_9633__75829.1731705493.jpg?c=2",
    category: "Actuators",
  },
  {
    id: "arduino_component_kit",
    name: "Component Kit for Arduino",
    description: "A starter pack of essential components for any Arduino project.",
    price: 7.95,
    quantity: 2,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/1115/2794/apip50rfd__51305.1554989268.jpg?c=2",
    category: "Kits",
  },

  // =================================================================
  // == Items from pishop.ca
  // =================================================================
  {
    id: "pi_l298_driver",
    name: "HW-095A L298 Stepper Motor Driver Module",
    description: "A robust driver for controlling two DC motors or one stepper motor.",
    price: 4.95,
    quantity: 10,
    max_quantity: 2,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/2600/7336/L298N-1__35075.1620848851.jpg?c=2",
    category: "Motors & Drivers",
  },
  {
    id: "pi_half_breadboard",
    name: "Half-Size Breadboard with Mounting Holes",
    description: "400-point breadboard, perfect for prototyping small to medium circuits.",
    price: 8.45,
    quantity: 10,
    max_quantity: 2,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/3335/10653/1995_1__07099.1682612984.jpg?c=2",
    category: "Prototyping",
  },
  {
    id: "pi_usbc_power",
    name: "USB-C Power Supply, 5.1V 3.0A, with On/Off Switch",
    description: "Official Raspberry Pi power supply, providing stable power.",
    price: 11.95,
    quantity: 10,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/2621/7494/DSC01464__11498.1744336692.gif?c=2",
    category: "Power",
  },
  {
    id: "pi_gear_motor_wheel",
    name: "Gear Motor With Wheel",
    description: "A simple and effective DC gear motor with a matching wheel.",
    price: 4.95,
    quantity: 4,
    max_quantity: 4,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/2606/7450/mot-320__29991.1622472869.jpg?c=2",
    category: "Motors & Drivers",
  },
  {
    id: "pi_micro_hdmi_cable",
    name: "Micro-HDMI to Standard HDMI Cable, 1m",
    description: "Connect your Raspberry Pi 4 to any standard HDMI display.",
    price: 6.95,
    quantity: 10,
    max_quantity: 1,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/2147/5664/2M-HDMI_MICRO_BLACK_e__07901.1582838868.jpg?c=2",
    category: "Cables",
  },

  // =================================================================
  // == Items from canadarobotix.com
  // =================================================================
  {
    id: "cr_micro_260_motor",
    name: "Micro 260 Hobby DC Motor",
    description: "A small, reliable DC motor for various hobbyist projects.",
    price: 1.99,
    quantity: 10,
    max_quantity: 4,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/329/13101/106_Square__59625.1745524510.png?c=2",
    category: "Motors & Drivers",
  },
  {
    id: "cr_sg90_servo_continuous",
    name: "Micro Continuous Rotation Servo (SG90)",
    description: "A micro servo modified for full 360-degree continuous rotation.",
    price: 4.99,
    quantity: 10,
    max_quantity: 4,
    image: "https://www.canadarobotix.com/cdn/shop/files/SG90_67ccc17d-67cb-481c-919c-2143483cb943_1024x1024@2x.jpg?v=1724177778",
    category: "Motors & Drivers",
  },

  // =================================================================
  // == Items from Sensor Kit v4.0 (x5)
  // =================================================================
  {
    id: "sensor_double_color_led",
    name: "Double Color LED",
    description: "A single LED that can emit two different colors.",
    price: 1.5,
    quantity: 5,
    max_quantity: 5,
    image: "https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/500x659/products/3193/10026/12903-01__70023.1675084616.jpg?c=2",
    category: "Sensors",
  },
  {
    id: "sensor_rgb_led",
    name: "RGB LED",
    description: "A single LED that can display a full range of colors.",
    price: 1.75,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_auto_flash_led",
    name: "Auto-Flash LED",
    description: "An LED that blinks automatically when powered.",
    price: 1.25,
    quantity: 5,
    max_quantity: 5,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_relay_module",
    name: "Relay Module",
    description: "A switch that can be controlled by an electrical signal.",
    price: 3.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_laser_emitter",
    name: "Laser Emitter",
    description: "A module that emits a small laser beam. Handle with care.",
    price: 4.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_button",
    name: "Button Module",
    description: "A simple pushbutton module for user input.",
    price: 1.5,
    quantity: 5,
    max_quantity: 5,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_tilt_switch",
    name: "Tilt Switch",
    description: "A sensor that detects orientation or inclination.",
    price: 2.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_vibration_switch",
    name: "Vibration Switch",
    description: "A sensor that detects motion or vibration.",
    price: 2.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_ir_receiver",
    name: "IR Receiver",
    description: "Receives signals from an infrared remote control.",
    price: 2.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_active_buzzer",
    name: "Active Buzzer",
    description: "Generates a tone when power is applied.",
    price: 2.25,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_passive_buzzer",
    name: "Passive Buzzer",
    description: "Generates tones of different frequencies.",
    price: 2.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_reed_switch",
    name: "Reed Switch",
    description: "A switch operated by a magnetic field.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_photo_interrupt",
    name: "Photo-interrupter",
    description: "Detects when an object passes through its slot.",
    price: 3.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_ad_da_pcf8591",
    name: "AD/DA Converter PCF8591",
    description: "Analog-to-Digital and Digital-to-Analog converter.",
    price: 5.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_raindrop",
    name: "Raindrop Sensor",
    description: "Detects raindrops and water presence.",
    price: 3.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_joystick_ps2",
    name: "PS2 Joystick Module",
    description: "A 2-axis joystick with a push-button.",
    price: 4.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_potentiometer",
    name: "Potentiometer Module",
    description: "A variable resistor for analog input.",
    price: 2.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_analog_hall",
    name: "Analog Hall Sensor",
    description: "Detects magnetic fields with analog output.",
    price: 3.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_hall_switch",
    name: "Hall Switch",
    description: "A digital switch that reacts to magnetic fields.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_analog_temp",
    name: "Analog Temperature Sensor",
    description: "Measures temperature with an analog output.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_thermistor",
    name: "Thermistor",
    description: "A resistor whose resistance changes with temperature.",
    price: 2.0,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_sound",
    name: "Sound Sensor",
    description: "Detects ambient sound levels.",
    price: 3.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_photoresistor",
    name: "Photoresistor",
    description: "A resistor that changes resistance based on light.",
    price: 1.5,
    quantity: 5,
    max_quantity: 5,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_flame",
    name: "Flame Sensor",
    description: "Detects fire and flame sources.",
    price: 3.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_gas",
    name: "Gas Sensor",
    description: "Detects the presence of various gases.",
    price: 4.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_remote_control",
    name: "Remote Control",
    description: "An infrared remote for controlling projects.",
    price: 3.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_touch_switch",
    name: "Touch Switch",
    description: "A capacitive touch sensor module.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_hc_sr04",
    name: "HC-SR04 Ultrasonic Sensor",
    description: "Measures distance using ultrasonic waves.",
    price: 4.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_ds18b20",
    name: "DS18B20 Temperature Sensor",
    description: "A digital temperature sensor.",
    price: 3.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_rotary_encoder",
    name: "Rotary Encoder",
    description: "A rotational sensor that can be used as a knob.",
    price: 4.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_humiture",
    name: "Humiture Sensor",
    description: "Measures both humidity and temperature.",
    price: 4.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_ir_obstacle",
    name: "IR Obstacle Sensor",
    description: "Detects objects using an infrared beam.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_1602_i2c",
    name: "1602 I2C LCD Display",
    description: "A 16x2 character LCD that uses the I2C protocol.",
    price: 8.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Displays",
  },
  {
    id: "sensor_bmp280_barometer",
    name: "BMP280 Barometer",
    description: "Measures atmospheric pressure.",
    price: 6.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_mpu6050",
    name: "MPU6050 Gyro/Accelerometer",
    description: "A 6-axis motion tracking device.",
    price: 7.0,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
  {
    id: "sensor_rtc_ds1302",
    name: "RTC-DS1302 Real-Time Clock",
    description: "Keeps track of the time even when powered off.",
    price: 4.5,
    quantity: 5,
    max_quantity: 1,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Components",
  },
  {
    id: "sensor_tracking",
    name: "Tracking Sensor",
    description: "A sensor for line-following robots.",
    price: 2.5,
    quantity: 5,
    max_quantity: 2,
    image: "https://www.hipi.io/wp-content/uploads/2021/08/LowQuality-Sensor-Kit.jpg",
    category: "Sensors",
  },
];
